PORTNAME=	sfwbar
DISTVERSION=	v1.0_beta9
CATEGORIES=	x11
MASTER_SITES=	https://github.com/LBCrion/sfwbar/archive/refs/tags

MAINTAINER=	tino.engel@mail.de
COMMENT=	A flexible taskbar application for wayland compositors
WWW=		https://github.com/LBCrion/sfwbar

.include <bsd.port.mk>